"""SQLAlchemy declarative base and shared column conventions (architecture G)."""

from __future__ import annotations

import datetime as dt
import uuid

from sqlalchemy import DateTime, MetaData
from sqlalchemy.orm import DeclarativeBase, MappedColumn, mapped_column
from sqlalchemy.types import Uuid

# Explicit naming convention so Alembic autogenerates stable, reviewable names
# for constraints and indexes instead of database-assigned ones.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base for every ReqPilot table."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def uuid_pk() -> MappedColumn[uuid.UUID]:
    """A UUID primary key generated by the application, not the database.

    Application-side generation means an entity has identity before it is
    flushed, which the audit service relies on: an audit event can reference a
    subject created in the same transaction (architecture T.1).
    """
    return mapped_column(Uuid, primary_key=True, default=uuid.uuid4)


def utc_now() -> dt.datetime:
    """Timezone-aware current time. Always UTC; never naive."""
    return dt.datetime.now(dt.UTC)


def created_at_column() -> MappedColumn[dt.datetime]:
    return mapped_column(DateTime(timezone=True), nullable=False, default=utc_now)
