"""Identifier types and conventions (architecture section G, C.7).

Primary keys are UUIDs generated by the application, so an entity has identity
before it is persisted - which matters for audit records that must reference a
subject created in the same transaction.

Distinct ``NewType`` aliases are used rather than a bare ``UUID`` so that passing
a project id where a run id is expected is a type error rather than a silent bug.
"""

from __future__ import annotations

from typing import NewType
from uuid import UUID, uuid4, uuid5

UserId = NewType("UserId", UUID)
ProjectId = NewType("ProjectId", UUID)
ActorId = NewType("ActorId", UUID)
GraphRunId = NewType("GraphRunId", UUID)
AgentRunId = NewType("AgentRunId", UUID)
AuditEventId = NewType("AuditEventId", UUID)
RequirementId = NewType("RequirementId", UUID)
RequirementVersionId = NewType("RequirementVersionId", UUID)
ApprovalTaskId = NewType("ApprovalTaskId", UUID)
ApprovalDecisionId = NewType("ApprovalDecisionId", UUID)
BaselineId = NewType("BaselineId", UUID)
TaskGroupId = NewType("TaskGroupId", UUID)


def new_uuid() -> UUID:
    """Return a fresh UUID for a new entity."""
    return uuid4()


def new_user_id() -> UserId:
    return UserId(uuid4())


def new_project_id() -> ProjectId:
    return ProjectId(uuid4())


def new_graph_run_id() -> GraphRunId:
    return GraphRunId(uuid4())


def new_agent_run_id() -> AgentRunId:
    return AgentRunId(uuid4())


def new_audit_event_id() -> AuditEventId:
    return AuditEventId(uuid4())


def thread_id_for(run_id: GraphRunId) -> str:
    """Return the LangGraph ``thread_id`` for a graph run (architecture C.7).

    One thread per run, never reused, always derived from the run id so that a
    checkpoint can always be traced back to its ``graph_run`` row.
    """
    return str(run_id)


def new_requirement_id() -> RequirementId:
    return RequirementId(uuid4())


def new_requirement_version_id() -> RequirementVersionId:
    return RequirementVersionId(uuid4())


def new_approval_task_id() -> ApprovalTaskId:
    return ApprovalTaskId(uuid4())


def new_approval_decision_id() -> ApprovalDecisionId:
    return ApprovalDecisionId(uuid4())


def new_baseline_id() -> BaselineId:
    return BaselineId(uuid4())


def new_task_group_id() -> TaskGroupId:
    """A submission groups its per-version approval tasks under one id.

    Architecture M.3 uses the same mechanism for G6's multi-role grouping.
    """
    return TaskGroupId(uuid4())


# ---------------------------------------------------------------------------
# Knowledge base and retrieval
# ---------------------------------------------------------------------------

NormativeSourceId = NewType("NormativeSourceId", UUID)
ControlId = NewType("ControlId", UUID)
KnowledgeItemId = NewType("KnowledgeItemId", UUID)
KnowledgeChunkId = NewType("KnowledgeChunkId", UUID)
EvidenceId = NewType("EvidenceId", UUID)
RetrievalId = NewType("RetrievalId", UUID)

#: Fixed namespace for derived chunk identities. Changing it would change every
#: chunk id, so it is a constant, not configuration.
_CHUNK_NAMESPACE = UUID("6f1c2d7e-3b4a-5c8d-9e0f-a1b2c3d4e5f6")


def chunk_id_for(
    item_id: UUID, ordinal: int, char_start: int, char_end: int, text_hash: str
) -> KnowledgeChunkId:
    """Return the deterministic identity of a knowledge chunk.

    Derived from what the chunk *is* - its item, position, span and content -
    rather than drawn at random. Chunking the same immutable item twice yields
    the same ids, so a chunk can be named stably and a repeated ingestion
    collides instead of silently duplicating.
    """
    return KnowledgeChunkId(
        uuid5(_CHUNK_NAMESPACE, f"{item_id}:{ordinal}:{char_start}:{char_end}:{text_hash}")
    )


def new_retrieval_id() -> RetrievalId:
    """One id per retrieval call; every evidence row it produces carries it."""
    return RetrievalId(uuid4())


# ---------------------------------------------------------------------------
# Project sources, extraction and classification
# ---------------------------------------------------------------------------

SourceDocumentId = NewType("SourceDocumentId", UUID)
SourceChunkId = NewType("SourceChunkId", UUID)
ExtractionCandidateId = NewType("ExtractionCandidateId", UUID)
ReviewItemId = NewType("ReviewItemId", UUID)

#: Fixed namespace for derived project-chunk identities; distinct from the
#: knowledge-chunk namespace so the two corpora can never share an id.
_SOURCE_CHUNK_NAMESPACE = UUID("0b9d4a61-7c2e-5f13-8a4d-2e6c9b1f7a30")


def source_chunk_id_for(
    document_id: UUID, ordinal: int, char_start: int, char_end: int, text_hash: str
) -> SourceChunkId:
    """Return the deterministic identity of a project-document segment.

    Derived from what the segment is, like :func:`chunk_id_for`, so the same
    immutable document always segments to the same ids and a requirement's
    source reference names a stable thing.
    """
    return SourceChunkId(
        uuid5(
            _SOURCE_CHUNK_NAMESPACE,
            f"{document_id}:{ordinal}:{char_start}:{char_end}:{text_hash}",
        )
    )
