"""Identifier types and conventions (architecture section G, C.7).

Primary keys are UUIDs generated by the application, so an entity has identity
before it is persisted - which matters for audit records that must reference a
subject created in the same transaction.

Distinct ``NewType`` aliases are used rather than a bare ``UUID`` so that passing
a project id where a run id is expected is a type error rather than a silent bug.
"""

from __future__ import annotations

from typing import NewType
from uuid import UUID, uuid4

UserId = NewType("UserId", UUID)
ProjectId = NewType("ProjectId", UUID)
ActorId = NewType("ActorId", UUID)
GraphRunId = NewType("GraphRunId", UUID)
AgentRunId = NewType("AgentRunId", UUID)
AuditEventId = NewType("AuditEventId", UUID)
RequirementId = NewType("RequirementId", UUID)
RequirementVersionId = NewType("RequirementVersionId", UUID)
ApprovalTaskId = NewType("ApprovalTaskId", UUID)
ApprovalDecisionId = NewType("ApprovalDecisionId", UUID)
BaselineId = NewType("BaselineId", UUID)
TaskGroupId = NewType("TaskGroupId", UUID)


def new_uuid() -> UUID:
    """Return a fresh UUID for a new entity."""
    return uuid4()


def new_user_id() -> UserId:
    return UserId(uuid4())


def new_project_id() -> ProjectId:
    return ProjectId(uuid4())


def new_graph_run_id() -> GraphRunId:
    return GraphRunId(uuid4())


def new_agent_run_id() -> AgentRunId:
    return AgentRunId(uuid4())


def new_audit_event_id() -> AuditEventId:
    return AuditEventId(uuid4())


def thread_id_for(run_id: GraphRunId) -> str:
    """Return the LangGraph ``thread_id`` for a graph run (architecture C.7).

    One thread per run, never reused, always derived from the run id so that a
    checkpoint can always be traced back to its ``graph_run`` row.
    """
    return str(run_id)


def new_requirement_id() -> RequirementId:
    return RequirementId(uuid4())


def new_requirement_version_id() -> RequirementVersionId:
    return RequirementVersionId(uuid4())


def new_approval_task_id() -> ApprovalTaskId:
    return ApprovalTaskId(uuid4())


def new_approval_decision_id() -> ApprovalDecisionId:
    return ApprovalDecisionId(uuid4())


def new_baseline_id() -> BaselineId:
    return BaselineId(uuid4())


def new_task_group_id() -> TaskGroupId:
    """A submission groups its per-version approval tasks under one id.

    Architecture M.3 uses the same mechanism for G6's multi-role grouping.
    """
    return TaskGroupId(uuid4())
