"""Identifier types and conventions (architecture section G, C.7).

Primary keys are UUIDs generated by the application, so an entity has identity
before it is persisted - which matters for audit records that must reference a
subject created in the same transaction.

Distinct ``NewType`` aliases are used rather than a bare ``UUID`` so that passing
a project id where a run id is expected is a type error rather than a silent bug.
"""

from __future__ import annotations

from typing import NewType
from uuid import UUID, uuid4

UserId = NewType("UserId", UUID)
ProjectId = NewType("ProjectId", UUID)
ActorId = NewType("ActorId", UUID)
GraphRunId = NewType("GraphRunId", UUID)
AgentRunId = NewType("AgentRunId", UUID)
AuditEventId = NewType("AuditEventId", UUID)


def new_uuid() -> UUID:
    """Return a fresh UUID for a new entity."""
    return uuid4()


def new_user_id() -> UserId:
    return UserId(uuid4())


def new_project_id() -> ProjectId:
    return ProjectId(uuid4())


def new_graph_run_id() -> GraphRunId:
    return GraphRunId(uuid4())


def new_agent_run_id() -> AgentRunId:
    return AgentRunId(uuid4())


def new_audit_event_id() -> AuditEventId:
    return AuditEventId(uuid4())


def thread_id_for(run_id: GraphRunId) -> str:
    """Return the LangGraph ``thread_id`` for a graph run (architecture C.7).

    One thread per run, never reused, always derived from the run id so that a
    checkpoint can always be traced back to its ``graph_run`` row.
    """
    return str(run_id)
